### ISSUE TITLE
Discussion: Default segment size limits

### ISSUE THREAD

**Issue by akxcv** [umbrellio/rollex#14]
Segments have default sizes. Rollex counters should be designed to resemble **physical** rolling counters as closely as possible. This means that **the number of digits in each segment is a constant**. 

To illustrate the point:
Let's say the counter starts at "10:10:10:10". What should the counter display after 1 second passes? Clearly, "10:10:10:**0**9". The zero is there because in the *real, physical rolling counter* digits cannot ever appear or disappear. What should the counter display after 1 day passes, then? A physical counter would display "09:10:10:10".

But what happens when the counter has to count down from, let's say, 200 days? By default, the counter should limit itself to 99 *displayed* days: "99:00:00:00". After 10 days, it will still show "99:00:00:00". However, if the user specifically desires not to limit the size of the segment, the counter should show "200:00:00:00". After 102 days, it should show "098:00:00:00". When there's only 1 day left, it should display "001:00:00:00".

And, if the counting direction is "up", the counter should show "000:00:00:00" initially, because it knows it'll have to get to 200 days before the counting stops.

What about non-decimal numerical bases? What should "days" be limited to by default? Let's say we're dealing with hexadecimals. Should the limit be "ff" (`(16 ^ 2) - 1`) or something else?

By the way, this will apply not only to "days", but to any segment that represents `maxPeriod`. For example, if `maxPeriod == "hours"`, and we have 78 hours to count, the counter will display "78:00:00", without limiting "hours" to 23.

**Comment by akxcv** [comment]
Actually, for a physical counter, the notion of "min and max digits" doesn't make sense. There is just "a number of digits". Thus, maxDigits and minDigits should be united into a single "digits" parameter. "0" would stand for "unlimited", positive values would mean "this segment always has N digits".

**Comment by JelF** [comment]
agree

**Comment by akxcv** [comment]
Closed by #13.
