### ISSUE TITLE
This project is someway incompatible with node 6

### ISSUE THREAD

**Issue by JelF** [umbrellio/rollex#18]
proves: https://gist.github.com/JelF/a814322b41af9f497d6048f3c89c37be

Toolchain should prevent running with node < 7 or either node 6 should be supported

**Comment by akxcv** [comment]
The problem is likely in global state in `test/unit/counter/ticking.test.js`. If you run any single spec in focus mode, it passes. If you run at least 2 specs, last one fails. My guess is it has to do with all the components not being unmounted at the end of each test.
