### ISSUE TITLE
Use singleton class instead of global objects

### ISSUE THREAD

**Issue by akxcv** [umbrellio/rollex#19]
Currently we use `window.rollexIntervals` object for making multiple counters run on a single interval. It would be better to rewrite this with a singleton class to avoid `window` pollution.

**Comment by JelF** [comment]
Fix of this should include fix of ```
    // FIXME: the following line is required. It shouldn't be. Something's wrong with global state.
    mount(<Counter seconds={10000} />)
``` in test/unit/counter/ticking.test.js

It is dependend things. Timers should be properly unmount after each test, not just deleted

**Comment by JelF** [comment]
please, assign yourself if you are already working

**Comment by akxcv** [comment]
I'm not working on this yet.
